### PR TITLE
Fix miscellaneous bugs and improve section handling for surface properties

### LINKED ISSUE #8: RAM_Toolkit: Need to add functionality for properly reading section properties and materials
Currently default materials are applied, and floor sections and beam sections are represented by Name, not a proper BHoM Section.

### LINKED ISSUE #139: RAM_Toolkit: Panels don't come out the way they came in
#### Description:
composite ribbed decks and non-composite flat slabs come out of RAM with the same properties, both ConstantThickness. When they're put back in, they both map to composite ribbed deck.

#### Steps to reproduce:
Create a non composite flat slab system, pull into BHoM, push back to a new model. slab will now be composite ribbed.

### LINKED ISSUE #147: RAM_Adapter: handling paths wrong
#### Description:
supplying a valid windows path to an empty RAM file can lead to the adapter throwing an invalid path error (it then displays a path with a weird mix of \ and // to a different location that was specified), then crashing Rhino.

#### Steps to reproduce:

Supply a path copied from an explorer window, such as "C:\Users\jtaylor\BuroHappold\Buildings and Habitats object Model - Scripts\BuroHappold_BHoM_v3.2\0018_RAM_Toolkit\0 Create Elements.rss"
with the quotes, and it will crash. If the quotation marks are not included, it doesn't crash.

### PR DESCRIPTION
**Pull request by enarhi**
### Issues addressed by this PR

Closes #8 
Closes #147 
Closes #139 

-Fixes filepath bug when the filepath includes quotes
-Adds additional section handling to address bugs when pushing and pulling sections associated with deck and slabs
-Fixes bugs related to unit conversion issues for cantilevered members and wall openings
-Fixed ZShift bug that prohibited contour loads from coming in on proper levels

### Test files
[0 RAM Create - read - update elements - Tutorial Round Trip.zip](https://github.com/BHoM/RAM_Toolkit/files/4808796/0.RAM.Create.-.read.-.update.elements.-.Tutorial.Round.Trip.zip)

### CODE REVIEW

File: RAM_Adapter/Convert/ToBHoM.cs [hunk 1]
```diff
@@ -617,12 +576,12 @@ public static Panel ToBHoMObject(this IWall ramWall)
 
             if (ramWall.eMaterial == EMATERIALTYPES.EWallPropConcreteMat)
             {
-                wallLabel = "Concrete " + wallThickness.ToString();
+                wallLabel = "Concrete " + ramWall.dThickness.ToString() + " in";
```
Comment (JosefTaylor) [inline RAM_Adapter/Convert/ToBHoM.cs:579]: use iProperty.DescriptionOrName() ?

**Comment by enarhi** [comment]
@JosefTaylor happy with this one, please re-review.

**Comment by enarhi** [comment]
@JosefTaylor @jean-lucjacksonBH this one is ready to go now, please review!
